// 全世界城市基础数据
// 说明：
// 1. 这里定义的是「单一权威数据源」，供目的地选择、AI 规划提示、地图查询等模块使用
// 2. 当前仅内置了常见热门城市示例，后续可通过脚本或数据导入方式扩展为「全世界城市」
// 3. 建议后续维护为独立的 JSON/数据库，再由构建脚本注入到本文件或以异步方式加载

export const WORLD_CITY_DATA = [
    // 亚洲 - 东亚
    {
      id: 'tokyo',
      name: '东京',
      englishName: 'Tokyo',
      country: '日本',
      countryCode: 'JP',
      lat: 35.6762,
      lng: 139.6503,
      timezone: 'Asia/Tokyo',
      region: 'Asia',
    },
    {
      id: 'seoul',
      name: '首尔',
      englishName: 'Seoul',
      country: '韩国',
      countryCode: 'KR',
      lat: 37.5665,
      lng: 126.978,
      timezone: 'Asia/Seoul',
      region: 'Asia',
    },
    {
      id: 'beijing',
      name: '北京',
      englishName: 'Beijing',
      country: '中国',
      countryCode: 'CN',
      lat: 39.9042,
      lng: 116.4074,
      timezone: 'Asia/Shanghai',
      region: 'Asia',
    },
    {
      id: 'shanghai',
      name: '上海',
      englishName: 'Shanghai',
      country: '中国',
      countryCode: 'CN',
      lat: 31.2304,
      lng: 121.4737,
      timezone: 'Asia/Shanghai',
      region: 'Asia',
    },
    {
      id: 'hongkong',
      name: '香港',
      englishName: 'Hong Kong',
      country: '中国',
      countryCode: 'CN',
      lat: 22.3193,
      lng: 114.1694,
      timezone: 'Asia/Hong_Kong',
      region: 'Asia',
    },
    {
      id: 'taipei',
      name: '台北',
      englishName: 'Taipei',
      country: '中国',
      countryCode: 'CN',
      lat: 25.033,
      lng: 121.5654,
      timezone: 'Asia/Taipei',
      region: 'Asia',
    },
    {
      id: 'osaka',
      name: '大阪',
      englishName: 'Osaka',
      country: '日本',
      countryCode: 'JP',
      lat: 34.6937,
      lng: 135.5023,
      timezone: 'Asia/Tokyo',
      region: 'Asia',
    },
  
    // 亚洲 - 东南亚
    {
      id: 'bangkok',
      name: '曼谷',
      englishName: 'Bangkok',
      country: '泰国',
      countryCode: 'TH',
      lat: 13.7563,
      lng: 100.5018,
      timezone: 'Asia/Bangkok',
      region: 'Asia',
    },
    {
      id: 'singapore',
      name: '新加坡',
      englishName: 'Singapore',
      country: '新加坡',
      countryCode: 'SG',
      lat: 1.3521,
      lng: 103.8198,
      timezone: 'Asia/Singapore',
      region: 'Asia',
    },
    {
      id: 'kualalumpur',
      name: '吉隆坡',
      englishName: 'Kuala Lumpur',
      country: '马来西亚',
      countryCode: 'MY',
      lat: 3.139,
      lng: 101.6869,
      timezone: 'Asia/Kuala_Lumpur',
      region: 'Asia',
    },
    {
      id: 'jakarta',
      name: '雅加达',
      englishName: 'Jakarta',
      country: '印度尼西亚',
      countryCode: 'ID',
      lat: -6.2088,
      lng: 106.8456,
      timezone: 'Asia/Jakarta',
      region: 'Asia',
    },
    {
      id: 'manila',
      name: '马尼拉',
      englishName: 'Manila',
      country: '菲律宾',
      countryCode: 'PH',
      lat: 14.5995,
      lng: 120.9842,
      timezone: 'Asia/Manila',
      region: 'Asia',
    },
  
    // 亚洲 - 南亚
    {
      id: 'delhi',
      name: '德里',
      englishName: 'Delhi',
      country: '印度',
      countryCode: 'IN',
      lat: 28.7041,
      lng: 77.1025,
      timezone: 'Asia/Kolkata',
      region: 'Asia',
    },
    {
      id: 'mumbai',
      name: '孟买',
      englishName: 'Mumbai',
      country: '印度',
      countryCode: 'IN',
      lat: 19.076,
      lng: 72.8777,
      timezone: 'Asia/Kolkata',
      region: 'Asia',
    },
    {
      id: 'karachi',
      name: '卡拉奇',
      englishName: 'Karachi',
      country: '巴基斯坦',
      countryCode: 'PK',
      lat: 24.8607,
      lng: 67.0011,
      timezone: 'Asia/Karachi',
      region: 'Asia',
    },
  
    // 亚洲 - 中东
    {
      id: 'dubai',
      name: '迪拜',
      englishName: 'Dubai',
      country: '阿联酋',
      countryCode: 'AE',
      lat: 25.2048,
      lng: 55.2708,
      timezone: 'Asia/Dubai',
      region: 'MiddleEast',
    },
    {
      id: 'riyadh',
      name: '利雅得',
      englishName: 'Riyadh',
      country: '沙特阿拉伯',
      countryCode: 'SA',
      lat: 24.7136,
      lng: 46.6753,
      timezone: 'Asia/Riyadh',
      region: 'MiddleEast',
    },
    {
      id: 'istanbul',
      name: '伊斯坦布尔',
      englishName: 'Istanbul',
      country: '土耳其',
      countryCode: 'TR',
      lat: 41.0082,
      lng: 28.9784,
      timezone: 'Europe/Istanbul',
      region: 'MiddleEast',
    },
  
    // 欧洲
    {
      id: 'london',
      name: '伦敦',
      englishName: 'London',
      country: '英国',
      countryCode: 'GB',
      lat: 51.5074,
      lng: -0.1278,
      timezone: 'Europe/London',
      region: 'Europe',
    },
    {
      id: 'paris',
      name: '巴黎',
      englishName: 'Paris',
      country: '法国',
      countryCode: 'FR',
      lat: 48.8566,
      lng: 2.3522,
      timezone: 'Europe/Paris',
      region: 'Europe',
    },
    {
      id: 'rome',
      name: '罗马',
      englishName: 'Rome',
      country: '意大利',
      countryCode: 'IT',
      lat: 41.9028,
      lng: 12.4964,
      timezone: 'Europe/Rome',
      region: 'Europe',
    },
    {
      id: 'barcelona',
      name: '巴塞罗那',
      englishName: 'Barcelona',
      country: '西班牙',
      countryCode: 'ES',
      lat: 41.3851,
      lng: 2.1734,
      timezone: 'Europe/Madrid',
      region: 'Europe',
    },
    {
      id: 'berlin',
      name: '柏林',
      englishName: 'Berlin',
      country: '德国',
      countryCode: 'DE',
      lat: 52.520,
      lng: 13.405,
      timezone: 'Europe/Berlin',
      region: 'Europe',
    },
    {
      id: 'moscow',
      name: '莫斯科',
      englishName: 'Moscow',
      country: '俄罗斯',
      countryCode: 'RU',
      lat: 55.7558,
      lng: 37.6173,
      timezone: 'Europe/Moscow',
      region: 'Europe',
    },
    {
      id: 'amsterdam',
      name: '阿姆斯特丹',
      englishName: 'Amsterdam',
      country: '荷兰',
      countryCode: 'NL',
      lat: 52.3676,
      lng: 4.9041,
      timezone: 'Europe/Amsterdam',
      region: 'Europe',
    },
  
    // 北美洲
    {
      id: 'newyork',
      name: '纽约',
      englishName: 'New York',
      country: '美国',
      countryCode: 'US',
      lat: 40.7128,
      lng: -74.006,
      timezone: 'America/New_York',
      region: 'NorthAmerica',
    },
    {
      id: 'losangeles',
      name: '洛杉矶',
      englishName: 'Los Angeles',
      country: '美国',
      countryCode: 'US',
      lat: 34.0522,
      lng: -118.2437,
      timezone: 'America/Los_Angeles',
      region: 'NorthAmerica',
    },
    {
      id: 'sanfrancisco',
      name: '旧金山',
      englishName: 'San Francisco',
      country: '美国',
      countryCode: 'US',
      lat: 37.7749,
      lng: -122.4194,
      timezone: 'America/Los_Angeles',
      region: 'NorthAmerica',
    },
    {
      id: 'toronto',
      name: '多伦多',
      englishName: 'Toronto',
      country: '加拿大',
      countryCode: 'CA',
      lat: 43.6532,
      lng: -79.3832,
      timezone: 'America/Toronto',
      region: 'NorthAmerica',
    },
    {
      id: 'mexicocity',
      name: '墨西哥城',
      englishName: 'Mexico City',
      country: '墨西哥',
      countryCode: 'MX',
      lat: 19.4326,
      lng: -99.1332,
      timezone: 'America/Mexico_City',
      region: 'NorthAmerica',
    },
  
    // 南美洲
    {
      id: 'sao-paulo',
      name: '圣保罗',
      englishName: 'Sao Paulo',
      country: '巴西',
      countryCode: 'BR',
      lat: -23.5505,
      lng: -46.6333,
      timezone: 'America/Sao_Paulo',
      region: 'SouthAmerica',
    },
    {
      id: 'buenosaires',
      name: '布宜诺斯艾利斯',
      englishName: 'Buenos Aires',
      country: '阿根廷',
      countryCode: 'AR',
      lat: -34.6037,
      lng: -58.3816,
      timezone: 'America/Argentina/Buenos_Aires',
      region: 'SouthAmerica',
    },
  
    // 非洲
    {
      id: 'cairo',
      name: '开罗',
      englishName: 'Cairo',
      country: '埃及',
      countryCode: 'EG',
      lat: 30.0444,
      lng: 31.2357,
      timezone: 'Africa/Cairo',
      region: 'Africa',
    },
    {
      id: 'johannesburg',
      name: '约翰内斯堡',
      englishName: 'Johannesburg',
      country: '南非',
      countryCode: 'ZA',
      lat: -26.2041,
      lng: 28.0473,
      timezone: 'Africa/Johannesburg',
      region: 'Africa',
    },
  
    // 大洋洲
    {
      id: 'sydney',
      name: '悉尼',
      englishName: 'Sydney',
      country: '澳大利亚',
      countryCode: 'AU',
      lat: -33.8688,
      lng: 151.2093,
      timezone: 'Australia/Sydney',
      region: 'Oceania',
    },
    {
      id: 'melbourne',
      name: '墨尔本',
      englishName: 'Melbourne',
      country: '澳大利亚',
      countryCode: 'AU',
      lat: -37.8136,
      lng: 144.9631,
      timezone: 'Australia/Melbourne',
      region: 'Oceania',
    },
    {
      id: 'auckland',
      name: '奥克兰',
      englishName: 'Auckland',
      country: '新西兰',
      countryCode: 'NZ',
      lat: -36.8485,
      lng: 174.7633,
      timezone: 'Pacific/Auckland',
      region: 'Oceania',
    },
  ];

